# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'SportingApp' do
  pod 'Kingfisher', '~> 7.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  
  # Pods for SportingApp

  target 'SportingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportingAppUITests' do
    # Pods for testing
  end

end
